import Head from 'next/head'
import './globals.css'
import { Open_Sans } from 'next/font/google'
const inter = Open_Sans({ subsets: ['latin'] })
export const metadata = {
  title: 'Saleems page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head> 
      <meta charset="utf-8" />  
        <meta name="viewport" content="width=device-width, initial-scale=1"/> 
      </Head>


      <body className={inter.className}>{children}</body>
    </html>
  )
}
